// Fort Severn coast-oriented AOI
// bearing 142.91 deg from north; 83.6 x 33.0 km; 2758 km2
// generated by 13_aoi_boundary.R on 2026-07-29
var aoi = ee.Geometry.Polygon([
    [[-88.317018, 56.278875],
     [-87.505682, 55.679857],
     [-87.082099, 55.858620],
     [-87.893435, 56.457638],
     [-88.317018, 56.278875]]
]);
Map.addLayer(aoi, {color: 'red'}, 'Fort Severn AOI');
Map.centerObject(aoi, 9);
