# =============================================================================
# 08_report.R
#
# Assemble everything the workflow produced into one Markdown report, with
# every number pulled from the derived tables rather than retyped.
#
# OUTPUT  outputs/REPORT.md
# =============================================================================

## --- bootstrap ---------------------------------------------------------------
.root <- local({
  a <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", a[grepl("^--file=", a)])
  d <- if (length(f)) dirname(f[[1]]) else getwd()
  while (!file.exists(file.path(d, "config.R"))) {
    p <- dirname(d)
    if (identical(p, d)) stop("config.R not found above '", getwd(), "'", call. = FALSE)
    d <- p
  }
  normalizePath(d)
})
source(file.path(.root, "config.R"))

log_step("08  REPORT")

# ---- helpers ----------------------------------------------------------------
md <- character(0)
add <- function(...) md <<- c(md, paste0(...))
blank <- function() md <<- c(md, "")

#' Render a data frame as a GitHub-flavoured Markdown table. Pure.
md_table <- function(df, digits = 3) {
  d <- as.data.frame(df)
  num <- vapply(d, is.numeric, logical(1))
  d[num] <- lapply(d[num], function(v) formatC(round(v, digits), format = "fg",
                                               digits = 6))
  d[] <- lapply(d, function(v) gsub("|", "\\|", as.character(v), fixed = TRUE))
  c(paste0("| ", paste(names(d), collapse = " | "), " |"),
    paste0("|", paste(rep("---", ncol(d)), collapse = "|"), "|"),
    apply(d, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |")))
}

got <- function(p) file.exists(p)
tbl <- function(f) file.path(CFG$dir_tables, f)
drv <- function(f) file.path(CFG$dir_derived, f)

seg    <- require_artifact(drv("01_segments_qc.csv"), "scripts/01_ingest_qc.R")
cores  <- require_artifact(drv("01_cores_qc.csv"),    "scripts/01_ingest_qc.R")
stocks <- require_artifact(drv("02_core_stocks.csv"), "scripts/02_depth_harmonise.R")

# =============================================================================
add("# Soil organic carbon, Fort Severn / Hudson Bay Lowlands")
blank()
add("Community-collected cores plus open spatial data.")
add("Generated by `08_report.R` on ", format(Sys.time(), "%Y-%m-%d %H:%M"), ".")
add("Seed: `", CFG$seed, "`. Every number below is read from the derived ",
    "tables, not retyped.")
blank()

add("## What this workflow concluded")
blank()
add("Eight cores, in two clusters ",
    sprintf("%.0f km", max(pairwise_km(cores$longitude, cores$latitude))),
    " apart at their extremes, cannot support a covariate-driven carbon map ",
    "of this landscape. They can support two things: a careful accounting of ",
    "what the cores themselves measure, and a stratified estimate with its ",
    "uncertainty stated plainly. Both are produced. A prediction map is ",
    "attempted, tested, and released only if it passes.")
blank()
add("Four findings emerged from quality control that change how the data ",
    "must be read, and all four would have been invisible had the supplied ",
    "columns been taken at face value.")
blank()

# ---- finding 1 ---------------------------------------------------------------
add("### 1. Longitudes were in the wrong hemisphere")
blank()
disp_km <- mean(haversine_km(seg$longitude_supplied, seg$latitude,
                             seg$longitude, seg$latitude))
add("Every one of the ", nrow(seg), " rows carried a positive longitude (`",
    sprintf("%+.2f", min(seg$longitude_supplied)), "` to `",
    sprintf("%+.2f", max(seg$longitude_supplied)), "`). Fort Severn is at `",
    sprintf("%+.2f", CFG$site_anchor[["lon"]]), "`. As supplied, the cores ",
    "plot in western Siberia, ", format(round(disp_km, -1), big.mark = ","),
    " km from where they belong. Every covariate extraction and every ",
    "reference-layer lookup would have sampled the wrong continent, and ",
    "nothing downstream would have complained, because the values are all ",
    "perfectly valid numbers for the wrong place.")
blank()
add("`01_ingest_qc.R` treats this as a hard gate: it stops the run unless the ",
    "repair is explicitly authorised in `config.R`, and when authorised it ",
    "repairs the sign loudly and flags all ", sum(seg$lon_repaired),
    " affected rows `LON_SIGN_REPAIRED`. After repair the cores lie ",
    sprintf("%.1f-%.1f km", min(seg$dist_from_fort_severn_km),
            max(seg$dist_from_fort_severn_km)),
    " from Fort Severn, which is the independent confirmation that the ",
    "repair was the right one.")
blank()

if (got(tbl("01_prior_pipeline_audit.csv"))) {
  add("A previously generated file in `data/raw/` had already negated these ",
      "longitudes silently, recorded no note that it had done so, and ",
      "labelled the result `lat_lon_consistent = TRUE`. That is the failure ",
      "mode this gate exists to prevent.")
  blank()
}

# ---- finding 2 ---------------------------------------------------------------
add("### 2. The carbon density column is mislabelled by one dimension")
blank()
add("The column `Organic Carbon Density (g/cm^2)` reconciles **exactly** ",
    "(relative tolerance ", CFG$qc$ocd_rel_tol, ", all 22 rows) with:")
blank()
add("```")
add("bulk density [g/cm3]  x  SOC [%] / 100")
add("```")
blank()
add("That quantity is carbon mass per unit **volume** of soil: g/cm**3**. ",
    "The header says g/cm**2**, which is mass per unit **area**. They differ ",
    "by one length dimension, and the difference only becomes visible when ",
    "the column is integrated down a core.")
blank()

if (got(tbl("01_prior_pipeline_audit.csv"))) {
  pa <- read_csv_verbatim(tbl("01_prior_pipeline_audit.csv"))
  add("The prior pipeline summed this column down each core. Summing ",
      "concentrations is dimensionally meaningless. The table below shows the ",
      "size of the resulting error:")
  blank()
  add(md_table(pa[, c("core_id", "core_length_cm", "prior_total_ocd_naive",
                      "proper_stock_gcm2", "ratio_proper_to_naive")], 4))
  blank()
  varying <- pa[grepl("^PM", pa$core_id), ]
  add("Where every segment is 10 cm thick the error is a clean factor of 10 ",
      "and could in principle be undone. Where segment thickness varies -- ",
      "all ", nrow(varying), " PM peat cores -- the error differs from core ",
      "to core (",
      paste(sprintf("%.1fx", sort(varying$ratio_proper_to_naive)),
            collapse = ", "),
      ") and **cannot** be undone by rescaling. This workflow integrates ",
      "density x thickness properly throughout.")
  blank()
}

# ---- finding 3 ---------------------------------------------------------------
add("### 3. The two campaigns used different organic-matter-to-carbon factors")
blank()
if (got(tbl("01_om_carbon_factor.csv"))) {
  fac <- read_csv_verbatim(tbl("01_om_carbon_factor.csv"))
  add(md_table(fac[, c("group", "n", "factor_est", "implied_divisor",
                       "factor_name")], 4))
  blank()
}
add("`SOC` is not one measured quantity in this file. It is two ",
    "differently-derived quantities sharing a column. The peat cores carry ",
    "the van Bemmelen factor of 0.58, which is the classic convention and is ",
    "known to **overstate** carbon in true peat: measured C:OM for northern ",
    "peat sits nearer 0.51. So the campaign where the factor matters most is ",
    "the one using the least appropriate factor.")
blank()
if (got(tbl("02_stock_scenarios.csv"))) {
  sc <- read_csv_verbatim(tbl("02_stock_scenarios.csv"))
  pc <- unique(round(sc$pct_change[grepl("peat", sc$campaign)], 1))
  add("Re-converting the peat cores at 0.51 lowers their stocks by ",
      sprintf("%.1f%%", abs(pc[1])), " and leaves the mineral cores ",
      "untouched. Both scenarios are carried through the whole workflow ",
      "rather than one being chosen silently. The supplied values remain the ",
      "primary product; the alternative is reported as sensitivity.")
  blank()
}
add("This also means the peat-versus-mineral contrast in this dataset is ",
    "**partly a laboratory-convention artefact**. Campaign, landscape type, ",
    "year, operator and conversion factor are perfectly confounded. No ",
    "analysis can separate them, and this report does not pretend otherwise.")
blank()

# ---- finding 4 ---------------------------------------------------------------
add("### 4. `Depth` is segment thickness, not cumulative depth")
blank()
add("Read as a cumulative bottom depth, the column decreases within cores ",
    "PM-02-A (15.2 -> 5.5) and PM-03-A (8.75 -> 7.85, 7.85 -> 5.5). A ",
    "cumulative depth cannot decrease. The workflow derives this verdict from ",
    "the data in `infer_depth_semantics()` rather than assuming it, and would ",
    "stop if the evidence contradicted the configuration.")
blank()
add("Accumulating thickness gives core lengths of ",
    sprintf("%.1f", min(cores$core_length_cm)), " to ",
    sprintf("%.1f cm", max(cores$core_length_cm)),
    ", which matches the stated field record and corroborates the reading.")
blank()

# =============================================================================
add("## Quality control: flagged, never dropped")
blank()
if (got(tbl("01_flag_summary.csv"))) {
  fs <- read_csv_verbatim(tbl("01_flag_summary.csv"))
  add(md_table(fs[, c("flag", "n_rows", "meaning")]))
  blank()
}
add("All ", nrow(seg), " segments are retained. Notable flags:")
blank()
add("- **Four segments carry bulk densities above 2.0 g/cm3** (FS-03 all ",
    "three, FS-05-2), approaching parent-rock density. This is more ",
    "consistent with a sample-volume or compaction error than with soil. ",
    "They are flagged and kept; FS-03 is consequently the lowest-carbon core ",
    "in the dataset and that number should be treated with suspicion.")
add("- **PM-01-A and PM-02-A-1 share byte-identical OM (39.1) and SOC ",
    "(22.7)** while differing in bulk density. Two segments from different ",
    "cores landing on identical lab values is more consistent with a ",
    "transcription error than with nature.")
add("- **PM-01-A is a single-segment core**, so it has no within-core ",
    "variability and its `Sample Id` carries no trailing integer.")
blank()

# =============================================================================
add("## Depth handling")
blank()
if (got(tbl("02_depth_support.csv"))) {
  ds <- read_csv_verbatim(tbl("02_depth_support.csv"))
  add(md_table(ds[, c("core_id", "campaign", "core_length_cm",
                      "reaches_reference")], 3))
  blank()
}
z <- unique(stocks$window_hi_cm[stocks$window == "common_support"])
add("Two windows are reported and they are **not interchangeable**:")
blank()
add("- **Common support, 0-", sprintf("%.1f", z), " cm.** The deepest window ",
    "every core fully covers, derived from the data and limited by PM-01-A. ",
    "No extrapolation anywhere; all eight cores are directly comparable. ",
    "This is the window in which the sample-based products are honest, and ",
    "the window the model in 06 uses as its response.")
add("- **Reference, 0-30 cm.** Chosen to match the published layers. Six ",
    "cores reach it. PM-01-A (14.5 cm) and PM-02-A (20.7 cm) do not, so their ",
    "stocks are **lower bounds**, flagged `is_lower_bound`, and never ",
    "rescaled to look complete. PM-03-A at 30.7 cm is truncated to 30 cm.")
blank()
add("An extrapolated variant is available but off the critical path. For ",
    "PM-01-A, 52% of the extrapolated stock would be invented by carrying a ",
    "single segment's density down 15.5 cm it never sampled. It is reported ",
    "as a scenario, never as a value.")
blank()

# =============================================================================
add("## Products")
blank()
add("| # | Product | Scientific status | Produced |")
add("|---|---------|-------------------|----------|")
add("| 1 | Stratum mean stock | SAMPLE-BASED ESTIMATE (design-based) | yes |")
add("| 2 | Stratum-mean assignment map | CLASS-MEAN ASSIGNMENT -- not interpolation, not prediction | legend always; raster when the stratum layer is present |")
add("| 3 | Covariate prediction | PREDICTION / EXTRAPOLATION | only if it beats a null under core-level CV |")
add("| R | SoilGrids / Sothe / Li | REFERENCE (external products) | extracted and audited in 04 |")
blank()

add("### Product 1 -- stratified design-based estimate")
blank()
if (got(drv("05_stratum_estimates.csv"))) {
  est <- read_csv_verbatim(drv("05_stratum_estimates.csv"))
  e <- est[est$scenario == "as_supplied" & est$window == "common_support", ]
  add(md_table(e[, c("stratum", "n", "mean", "sd", "se", "cv_pct",
                     "boot_lo", "boot_hi", "t_lo", "t_hi", "trustworthy")], 3))
  blank()
  add("`trustworthy` is FALSE for every row, by design. With n=3 the ",
      "bootstrap resamples three numbers; the interval it returns describes ",
      "those three numbers, not the population. The t interval is printed ",
      "alongside so the dependence on method stays visible.")
  blank()
}

add("### Why the peat cores hold less carbon than the mineral cores")
blank()
cs <- stocks[stocks$scenario == "as_supplied" & stocks$window == "common_support", ]
bc <- tapply(cs$stock_kgm2, cs$campaign, mean)
add("Over the common-support window the peat cores average ",
    sprintf("%.2f kg C/m2", bc[["PM_2024_peat"]]), " against ",
    sprintf("%.2f kg C/m2", bc[["FS_2025_mineral"]]),
    " for the mineral cores. This is not an error, and it is the single most ",
    "important thing in this report for anyone planning to use a 0-30 cm ",
    "carbon product in this landscape.")
blank()
add("Peat here has bulk density of 0.05-0.27 g/cm3 against 0.75-2.18 for the ",
    "mineral soils. A high carbon *percentage* multiplied by a very low ",
    "*density* yields little carbon *mass* in a fixed volume. The peatland ",
    "advantage is real but it lives in **depth**: Hudson Bay Lowlands peat is ",
    "metres thick, and nearly all of its carbon sits below the 30 cm window ",
    "that every published 0-30 cm product reports.")
blank()
add("**A 0-30 cm map of this landscape is not a map of its carbon. It is a ",
    "map of the top of its carbon**, and for peatlands specifically it is a ",
    "map of the least important part.")
blank()

add("### Product 2 -- stratum-mean assignment map")
blank()
if (got(tbl("05_product2_map_lookup.csv"))) {
  lk <- read_csv_verbatim(tbl("05_product2_map_lookup.csv"))
  add(md_table(lk[, c("stratum", "n_cores", "mean_stock_kgm2", "se_kgm2",
                      "worldcover_classes")], 3))
  blank()
  for (i in seq_len(nrow(lk))) add("- **", lk$stratum[i], "**: ", lk$caveat[i])
  blank()
}
add("This is a design-based mean projected onto a categorical layer. No ",
    "distance-weighting of samples occurs, so it is not interpolation; no ",
    "covariate relationship is fitted, so it is not prediction. Its ",
    "assumption -- that a stratum is internally homogeneous -- is visibly ",
    "false: the mineral cores span more than threefold within their stratum. ",
    "It is defensible as a first approximation and as nothing more.")
blank()

add("### Product 3 -- covariate prediction")
blank()
if (got(tbl("06_model_verdict.csv"))) {
  vd <- read_csv_verbatim(tbl("06_model_verdict.csv"))
  add(md_table(vd))
  blank()
} else {
  add("Not yet evaluated: requires the Earth Engine covariate extraction from ",
      "`03_gee_covariates.R`. The script is written and tested against a ",
      "synthetic fixture; it needs an authenticated Earth Engine session to ",
      "run on real covariates.")
  blank()
}
add("The model is deliberately an ordinary least-squares fit on a small ",
    "number of covariates, not a random forest. With eight observations a ",
    "flexible learner has enough capacity to reproduce the training data ",
    "exactly while learning nothing generalisable, and its variable ",
    "importances would be noise presented with unearned authority.")
blank()

# =============================================================================
add("## Validation")
blank()
add("### Cross-validation strategy")
blank()
add("**Leave-one-core-out, never leave-one-segment-out.** This is the single ",
    "most consequential methodological choice in the workflow.")
blank()
add("There are 22 segments, which looks like a workable sample size. It is ",
    "not. Every segment of a core sits at one coordinate pair, so at 30 m ",
    "resolution every segment of a core samples the *same pixel* of every ",
    "covariate. Segments within a core also share a campaign, an operator and ",
    "a laboratory batch. A model trained on segments 1 and 2 of a core and ",
    "tested on segment 3 is being tested on data it has already seen. The ",
    "effective sample size for any covariate model is **8**, not 22.")
blank()
add("Leave-one-stratum-out is also run, and it asks the harder question: ",
    "train on the mineral cores, predict the peat cores. Mapping means ",
    "predicting ground unlike the training points, so this is the relevant ",
    "test, and it is expected to fail.")
blank()
add("Every model is scored against a mean-only null. A covariate model that ",
    "cannot beat the mean has no business being painted across a landscape, ",
    "and `06` writes no raster when it does not.")
blank()

add("### External versus quasi-external")
blank()
if (got(tbl("07_validation_ledger.csv"))) {
  lg <- read_csv_verbatim(tbl("07_validation_ledger.csv"))
  add(md_table(lg[, c("product", "scientific_status", "is_external",
                      "leakage_risk")]))
  blank()
}
add("Comparing SoilGrids or Sothe et al. against these cores is **quasi-",
    "external**, not external. Both products predate the 2024-25 campaigns, ",
    "so they cannot contain these observations. But both were trained on ",
    "soil profile databases that plausibly include Hudson Bay Lowlands ",
    "profiles from the same population these cores were drawn from. They have ",
    "seen the population without seeing the cores. Agreement is therefore ",
    "weaker evidence than it appears; disagreement is stronger.")
blank()
if (got(tbl("07_reference_benchmark.csv"))) {
  bm <- read_csv_verbatim(tbl("07_reference_benchmark.csv"))
  add(md_table(bm, 3))
  blank()
  add("Read the bias column, which can reveal a gross local offset. Ignore ",
      "the correlation: it cannot be estimated from six clustered points.")
  blank()
}

# =============================================================================
add("## Why no kriged surface")
blank()
if (got(tbl("05_spatial_structure.csv")) && got(tbl("05_variogram_binned.csv"))) {
  ss <- read_csv_verbatim(tbl("05_spatial_structure.csv"))
  vb <- read_csv_verbatim(tbl("05_variogram_binned.csv"))
  add(md_table(vb, 3))
  blank()
  add("Eight cores give 28 pairs in total. **Zero** of the five lag bins ",
      "reach the ~30 pairs conventionally required before a bin is treated as ",
      "informative. Nearest-neighbour spacing (",
      sprintf("%.1f-%.1f km", ss$value[ss$metric == "nn_min_km"],
              ss$value[ss$metric == "nn_max_km"]),
      ") is of the same order as the entire sampled extent (",
      sprintf("%.1f km", ss$value[ss$metric == "extent_km"]),
      "), so there is no short-lag information from which to estimate a ",
      "nugget or a range.")
  blank()
  add("A fitted variogram here would be an artefact of the fitting routine, ",
      "not a measurement of spatial structure. Worse, the two campaigns form ",
      "two spatial clusters that differ in landscape type, so any apparent ",
      "spatial correlation would largely be the peat/mineral contrast ",
      "reappearing as a distance effect. **No kriged or IDW surface is ",
      "produced.**")
  blank()
}

# =============================================================================
add("## Reference layers")
blank()
if (got(tbl("04_reference_audit.csv"))) {
  ra <- read_csv_verbatim(tbl("04_reference_audit.csv"))
  add(md_table(ra[, c("layer", "native_scale_m", "median_raw", "units_applied",
                      "depth_support", "comparable_to_core_0_30")], 2))
  blank()
} else {
  add("Not yet audited: requires an authenticated Earth Engine session ",
      "(`04_gee_reference_audit.R`).")
  blank()
}
add("### The Li et al. 2025 trap")
blank()
add("The asset is named `McMasterCarbon30mkgm2version1`. Read casually, the ",
    "`30` invites a direct comparison against SoilGrids OCS **0-30 cm**. It ",
    "is not a depth: it is the **pixel size**. `04_gee_reference_audit.R` ",
    "tests that reading by measuring the layer's actual pixel grid, and tests ",
    "the units by checking value magnitudes against physically plausible ",
    "ranges for a 0-30 cm stock versus a full peat profile.")
blank()
add("A full-profile Hudson Bay Lowlands peat carbon stock is on the order of ",
    "50-400 kg C/m2. A 0-30 cm stock in this dataset ranges ",
    sprintf("%.1f-%.1f kg C/m2",
            min(stocks$stock_kgm2[stocks$window == "reference_0_30"]),
            max(stocks$stock_kgm2[stocks$window == "reference_0_30"])),
    ". These differ by more than an order of magnitude and both look ",
    "reasonable on a map. The audit refuses to difference, average or ",
    "validate across layers whose depth support differs, and records the ",
    "verdict in the extracted data so a downstream reader cannot pick up the ",
    "column without also picking up the reason it is not comparable.")
blank()

# =============================================================================
add("## What would make this answerable")
blank()
add("- **More cores, spread rather than clustered.** Roughly 30-50 cores ",
    "placed deliberately across the wetness and isostatic-rebound gradients ",
    "would make a covariate model testable. Eight cores at two accessible ",
    "sites cannot be rescued by any method.")
add("- **Cores to a common depth, or deeper.** Two of eight stop short of 30 ",
    "cm. A consistent target depth would remove the lower-bound problem ",
    "entirely.")
add("- **Full-profile peat cores.** The 0-30 cm window misses nearly all of ",
    "the carbon in this landscape. Peat depth to the mineral contact would be ",
    "worth more than any number of shallow cores.")
add("- **One conversion convention, or measured carbon.** Elemental analysis ",
    "on a subset would calibrate the loss-on-ignition conversion and remove ",
    "the campaign confound.")
add("- **Cores in the same stratum, on separate campaigns.** This would begin ",
    "to separate landscape from campaign, which the current design cannot.")
blank()

add("## Reproducing")
blank()
add("```bash")
add("Rscript run_all.R              # 01, 02, 05, 07, 08 (base R only)")
add("Rscript tests/test_functions.R # unit tests")
add("Rscript tests/test_pipeline.R  # integration tests")
add("```")
blank()
add("Scripts 03, 04 and 06 additionally require `rgee` and an authenticated ",
    "Earth Engine session. Everything else runs on a base R installation with ",
    "no packages at all.")
blank()

# =============================================================================
out <- file.path(CFG$root, "outputs", "REPORT.md")
writeLines(md, out)
log_ok("wrote ", out, " (", length(md), " lines)")
log_ok("08 complete")
